"""Add value to parameter_search

Revision ID: 67e5d51561a9
Revises: d55f67c9531d
Create Date: 2025-01-11 18:36:38.156038

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67e5d51561a9"
down_revision: Union[str, None] = "d55f67c9531d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "parameter", ["id"])
    op.add_column("parameter_search", sa.Column("value", sa.String(), nullable=False))
    op.create_unique_constraint(None, "user", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("parameter_search", "value")
    op.drop_constraint(None, "parameter", type_="unique")
    # ### end Alembic commands ###
